Repository prgrms-be-devcourse/NBE3-4-1-Team01, pull requests merged in 2025-01, with the labels that each got.

#6 [Feat] Product 엔티티 추가
  src/main/java/com/programmers/cafe/entity/Product.java
Labels: feature

#9 [Feat] 상품 수정 API 구현
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/java/com/programmers/cafe/dto/ProductRequestDto.java
  src/main/java/com/programmers/cafe/dto/ProductResponseDto.java
  src/main/java/com/programmers/cafe/entity/Product.java
  src/main/java/com/programmers/cafe/repository/ProductRepository.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: feature, test

#13 주문 조회 화면 구현
  build.gradle
  src/main/java/com/programmers/cafe/CafeApplication.java
  src/main/java/com/programmers/cafe/controller/OrderCheckController.java
  src/main/java/com/programmers/cafe/entity/Order.java
  src/main/java/com/programmers/cafe/repository/OrderRepository.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/resources/application.yml
  src/main/resources/static/bootstrap.min.css
  src/main/resources/static/bootstrap.min.js
  src/main/resources/templates/order_check.html
Labels: feature

#14 Feature/상품조회 API
  Invalidate
  docker-compose.yml
  init.sql
  src/main/java/com/programmers/cafe/CafeApplication.java
  src/main/java/com/programmers/cafe/controller/HomeController.java
  src/main/java/com/programmers/cafe/entity/Product.java
  src/main/java/com/programmers/cafe/repository/ProductRepository.java
  src/main/java/com/programmers/cafe/service/DataNotFoundException.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/main/resources/application.yml
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: feature, test

#18 [Fix] Exception 패키지 분리 및 테스트 코드 수정
  src/main/java/com/programmers/cafe/entity/Product.java
  src/main/java/com/programmers/cafe/exception/DataNotFoundException.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: refactor, test

#19 [FIX]readonly 추가
  src/main/java/com/programmers/cafe/repository/OrderRepository.java
  src/main/java/com/programmers/cafe/repository/ProductRepository.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/main/resources/application.yml
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: refactor

#20 [Feat] 상품 삭제 API 구현
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: feature, test

#24 [Feat] 주문 수정 기능 구현
  build.gradle
  src/main/java/com/programmers/cafe/controller/OrderCheckController.java
  src/main/java/com/programmers/cafe/entity/Order.java
  src/main/java/com/programmers/cafe/entity/Product.java
  src/main/java/com/programmers/cafe/entity/ProductOrder.java
  src/main/java/com/programmers/cafe/repository/ProductOrderRepository.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/java/com/programmers/cafe/service/ProductOrderService.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/templates/order_check.html
  src/main/resources/templates/order_modify.html
  src/test/java/com/programmers/cafe/ProductOrderServiceTest.java
Labels: feature, test

#28 [Fix] Product 테스트 코드 충돌 해결
  src/test/java/com/programmers/cafe/service/ProductOrderServiceTest.java
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: refactor, fix

#31 [Feat] 상품생성
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/java/com/programmers/cafe/dto/ProductRequestDto.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/main/resources/templates/product_create.html
Labels: feature

#33 [Fix] product/create -> create
  src/main/java/com/programmers/cafe/controller/ProductController.java
Labels: fix

#35 [Feat] admin 페이지
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/resources/templates/admin_product.html
Labels: feature

#42 [Fix]서비스로만 기본 디비 구성
  src/main/java/com/programmers/cafe/SetBaseDb.java
Labels: fix

#39 [Feat] 상품 생성 페이지
  src/main/resources/templates/product_create.html
Labels: feature

#40 [Feat] 주문 조회 페이지 개선
  src/main/resources/application.yml
  src/main/resources/templates/order_check.html
Labels: feature

#47 [Feat] admin 페이지
  src/main/resources/templates/admin_product.html
Labels: feature

#50 [Feat] 상품 생성 화면 구현
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/resources/static/css/bootstrap-grid.css
  src/main/resources/static/css/bootstrap-grid.css.map
  src/main/resources/static/css/bootstrap-grid.min.css
  src/main/resources/static/css/bootstrap-grid.min.css.map
  src/main/resources/static/css/bootstrap-reboot.css
  src/main/resources/static/css/bootstrap-reboot.css.map
  src/main/resources/static/css/bootstrap-reboot.min.css
  src/main/resources/static/css/bootstrap-reboot.min.css.map
  src/main/resources/static/css/bootstrap.css
  src/main/resources/static/css/bootstrap.css.map
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/bootstrap.min.css.map
  src/main/resources/static/css/jumbotron-narrow.css
  src/main/resources/static/images/columbia.jpeg
  src/main/resources/static/js/bootstrap.bundle.js
  src/main/resources/static/js/bootstrap.bundle.js.map
  src/main/resources/static/js/bootstrap.bundle.min.js
  src/main/resources/static/js/bootstrap.bundle.min.js.map
  src/main/resources/static/js/bootstrap.js
  src/main/resources/static/js/bootstrap.js.map
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/bootstrap.min.js.map
  src/main/resources/templates/fragments/bodyHeader.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/product_create.html
Labels: feature

#52 주문 관련 Entity를 DTO로 변환, 주문 수정 취소 버튼 추가
  src/main/java/com/programmers/cafe/controller/OrderCheckController.java
  src/main/java/com/programmers/cafe/dto/OrderDto.java
  src/main/java/com/programmers/cafe/dto/ProductOrderDto.java
  src/main/java/com/programmers/cafe/entity/Order.java
  src/main/java/com/programmers/cafe/repository/ProductOrderRepository.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/java/com/programmers/cafe/service/ProductOrderService.java
  src/main/resources/templates/order_modify.html
  src/test/java/com/programmers/cafe/service/ProductOrderServiceTest.java
Labels: feature, test, fix

#55 [Feat] 상품 수정 화면 구현
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/main/resources/templates/product_modify.html
Labels: feature

#56 [Feat] 주문 목록 페이징 구현
  src/main/java/com/programmers/cafe/controller/OrderCheckController.java
  src/main/java/com/programmers/cafe/repository/OrderRepository.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/resources/templates/order_check.html
Labels: feature

#59 [Fix] 기존 '/product' URI를 '/admin/product' URI로 변경
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/resources/templates/admin_product.html
  src/main/resources/templates/admin_product_create.html
  src/main/resources/templates/admin_product_modify.html
Labels: fix

#64 [Feat] 상품 삭제, 수정 버튼 기능
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/resources/templates/admin_product.html
Labels: feature

#66 [Feat] 주문 생성 기능
  src/main/java/com/programmers/cafe/CafeApplication.java
  src/main/java/com/programmers/cafe/controller/HomeController.java
  src/main/java/com/programmers/cafe/controller/OrderController.java
  src/main/java/com/programmers/cafe/dto/OrderRequestDto.java
  src/main/java/com/programmers/cafe/entity/Order.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/java/com/programmers/cafe/service/OrderStatusScheduler.java
  src/main/resources/templates/order_create.html
Labels: feature

#68 [Feat] 상품 삭제 전 안내메세지 출력
  src/main/resources/templates/admin_product.html
Labels: feature

#73 [Feat] Admin 페이지 페이징 기능
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/resources/templates/admin_product.html
Labels: feature

#70 [Feat] 주문 상세 페이지 도입
  src/main/java/com/programmers/cafe/controller/OrderCheckController.java
  src/main/java/com/programmers/cafe/dto/OrderFilterDto.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/resources/templates/order_check.html
  src/main/resources/templates/order_info.html
Labels: feature

#71 [Feat]주문 생성 기능 API
  src/main/java/com/programmers/cafe/controller/HomeController.java
  src/main/java/com/programmers/cafe/dto/OrderRequest.java
  src/main/java/com/programmers/cafe/dto/ProductOrderRequest.java
  src/main/java/com/programmers/cafe/service/CreateOrderService.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/main/resources/templates/product_list.html
Labels: feature, fix

#76 [Fix] 주문 조회 test데이터 수정
  src/test/java/com/programmers/cafe/service/OrderServiceTest.java
Labels: fix

#80 [REFACTOR] 배송 상태를 enum class로 관리하도록 수정
  src/main/java/com/programmers/cafe/dto/OrderDto.java
  src/main/java/com/programmers/cafe/dto/OrderFilterDto.java
  src/main/java/com/programmers/cafe/entity/Order.java
  src/main/java/com/programmers/cafe/global/DeliveryStatus.java
  src/main/java/com/programmers/cafe/repository/OrderRepository.java
  src/main/java/com/programmers/cafe/service/CreateOrderService.java
  src/main/java/com/programmers/cafe/service/OrderService.java
  src/main/java/com/programmers/cafe/service/OrderStatusScheduler.java
  src/main/resources/templates/order_check.html
Labels: refactor

#84 [FIX] 주문 상세 화면이 제대로 표시되도록 수정
  src/main/resources/templates/order_info.html
Labels: fix

#85 [Fix] admin 페이지 수정
  src/main/resources/templates/admin_product.html
Labels: fix

#88 [Feat] 상품 이미지 추가
  src/main/java/com/programmers/cafe/SetBaseDb.java
  src/main/java/com/programmers/cafe/controller/ProductController.java
  src/main/resources/static/images/Brazil_Serra_Do_Caparaó.jpeg
  src/main/resources/static/images/Colombia_Quindio.webp
  src/main/resources/static/images/Columbia_Nariñó.jpeg
  src/main/resources/static/images/Ethiopia_Sidamo.jpg
  src/main/resources/templates/admin_product.html
  src/main/resources/templates/admin_product_create.html
  src/main/resources/templates/admin_product_modify.html
Labels: feature, fix

#95 [Fix] 상품 삭제 시, soft delete 되도록 수정
  src/main/java/com/programmers/cafe/dto/ProductRequestDto.java
  src/main/java/com/programmers/cafe/dto/ProductResponseDto.java
  src/main/java/com/programmers/cafe/entity/Product.java
  src/main/java/com/programmers/cafe/service/ProductService.java
  src/test/java/com/programmers/cafe/service/ProductServiceTest.java
Labels: fix

#98 [Fix] admin 페이지 Button icon
  src/main/resources/templates/admin_product.html
Labels: fix
